version: '3.7'
services:
  licensingservice:
    image: ostock/licensing-service:latest
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "licenseservice"

  configserver:
    image: configserver/configserver:latest
    ports:
      - 8071:8071
    networks:
      backend:
        aliases:
          - "configserver"

networks:
  backend:
    driver: bridge