spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        # 로컬 구성 정보: classpath 위치나 파일 시스템의 위치가 될 수 있다.
        native:
          # 특정 파일 시스템에서 폴더를 읽어 온다.
          #          search-locations: file:///Users/illary.huaylupo
          search-locations: classpath:/config
    # 파일 서버에서는 리프레시가 안 되는 걸로 보임
    refresh:
      enabled: false

server:
  port: 8071
