version: '3.7'
services:
  configserver:
    image: configserver/configserver:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
            - "configserver"

networks:
  backend:
    driver: bridge
    name: backend